sudo: required
language: generic

services:
    - docker

script:
    - wget -O- https://raw.githubusercontent.com/harisvsulaiman/element-build/master/script.sh | sh -

branches:
except:
    - /^debian\/\d/
